// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6orfj6dIf6hJUThokWy26nZYynlIZbf4',
    appId: '1:170901196685:web:8ba38c4383ad33d557b7c4',
    messagingSenderId: '170901196685',
    projectId: 'stryker-e328a',
    authDomain: 'stryker-e328a.firebaseapp.com',
    storageBucket: 'stryker-e328a.appspot.com',
    measurementId: 'G-E9Z4VC8CWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx6MYaOotU-4lb9Ybra_ZYEYSW063Dp_A',
    appId: '1:170901196685:android:ad27e4225ae8754e57b7c4',
    messagingSenderId: '170901196685',
    projectId: 'stryker-e328a',
    storageBucket: 'stryker-e328a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-l6N34AhfFB8_fA670K5O_UuNse2usY',
    appId: '1:170901196685:ios:e85241df47321f8357b7c4',
    messagingSenderId: '170901196685',
    projectId: 'stryker-e328a',
    storageBucket: 'stryker-e328a.appspot.com',
    iosClientId: '170901196685-26nb0bik471jmih91cj2pb87jrc6kmbe.apps.googleusercontent.com',
    iosBundleId: 'com.app.stryker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-l6N34AhfFB8_fA670K5O_UuNse2usY',
    appId: '1:170901196685:ios:e85241df47321f8357b7c4',
    messagingSenderId: '170901196685',
    projectId: 'stryker-e328a',
    storageBucket: 'stryker-e328a.appspot.com',
    iosClientId: '170901196685-26nb0bik471jmih91cj2pb87jrc6kmbe.apps.googleusercontent.com',
    iosBundleId: 'com.app.stryker',
  );
}
